name: release publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu

      - name: Build
        uses: gradle/actions/setup-gradle@v4
        with:
          arguments: shadowJar

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*
